### PR TITLE
Remove 'yarn.lock'

### PR DESCRIPTION
**Pull request by vince-fugnitto**
**Description**

Remove the `yarn.lock` file (and it's generation) in order to not be troubled with dependency pinning and benefit from changes from upstream.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Shouldn't we wait after the 0.11 release before updating the yarn.lock for the theia-cpp-extensions, then we could use the "latest" tag for theia instead of using "0.11.0-next.8119a88f"
> According to the PR description, you wanted to use the "latest"

I wanted to update the lock since it was pinning Theia versions (mainly electron) that had an issue with CI.

**Comment by marcdumais-work** [comment]
Vince, which strategy did you use to update yarn.lock?

**Comment by vince-fugnitto** [comment]
> Vince, which strategy did you use to update yarn.lock?

I removed the entries of `@theia` and rebuilt.
The command `yarn upgrade --pattern='@theia'` was not working correctly for me.

**Comment by vince-fugnitto** [comment]
@lmcbout I redid the changes for after the release.
I'll wait to see if CI still passes successfully :)

**Comment by vince-fugnitto** [comment]
@lmcbout @marcdumais-work is there anything I'd need to resolve or fix before merging?

**Comment by lmcbout** [comment]
@vince-fugnitto Do you want to use @theia/... **0.12.0-next...** or **latest** version?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Do you want to use @theia/... **0.12.0-next...** or **latest** version?

I don't manually update the yarn dependencies, it is what they pull.
The `package.json` points to `next`: 

https://github.com/eclipse-theia/theia-cpp-extensions/blob/644c626c57aa1a69d654bda9b6b55fccd061ade0/packages/cpp-debug/package.json#L6

**Comment by lmcbout** [comment]
To have a more stable release for those extensions, should we use "next" or latest" in package.json?
CON: we will need to update the version after each release
PRO: the extensions should be stable for a month, not changing all the times after each PR

If we start publishing the extensions after each Theia release every month, then may be the "latest" should be used ! otherwise we should maintain "next"

**Comment by vince-fugnitto** [comment]
> To have a more stable release for those extensions, should we use "next" or latest" in package.json?
> CON: we will need to update the version after each release
> PRO: the extensions should be stable for a month, not changing all the times after each PR
> 
> If we start publishing the extensions after each Theia release every month, then may be the "latest" should be used ! otherwise we should maintain "next"

For all our repos I believe we follow the convention of using `next`.

**Comment by vince-fugnitto** [comment]
@lmcbout the `yarn.lock` file has been removed.

**Comment by lmcbout** [comment]
Looks fine with me,

**Comment by vince-fugnitto** [comment]
Thank you @marcdumais-work @lmcbout

**Pull request merged**
