### PR TITLE
Replace AppVeyor with Travis CI for Windows

### PR DESCRIPTION
**Pull request by vince-fugnitto**
- Replaces `AppVeyor` with `Travis CI` for Windows
- Remove `appveyor.yml`
- Update `travis.yml` to include `os: windows` build.
- Add badges for `gitpod`, `travis` and `bugs`.

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
With this change, we now get the badges present on the README:

Screen Shot 2019-09-13 at 1 06 13 PM

**Comment by vince-fugnitto** [comment]
Maybe someone can help regarding the [error](https://travis-ci.com/eclipse-theia/theia-cpp-extensions/jobs/234930847#L165-L172).

**Comment by vince-fugnitto** [comment]
There seems to be an [issue](https://travis-ci.com/eclipse-theia/theia-cpp-extensions/jobs/234930847#L165) with the `windows` build.
After discussion with @marechal-p it looks to be an issue with `yarn` and what it outputs. (https://github.com/yarnpkg/yarn/issues/4564)

As you can see the following line: 
`Error: Cannot find module 'C:\Users\travis\build\eclipse-theia\theia-cpp-extensions\node_modules\node_modules\@theia\debug\bin\download-adapters.js'`
Contains **node_modules** twice.

**Comment by lmcbout** [comment]
@vince-fugnitto Are you planning to add the `preinstall` to fix the window compilation
https://github.com/yarnpkg/yarn/issues/4564

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Are you planning to add the `preinstall` to fix the window compilation
> [yarnpkg/yarn#4564](https://github.com/yarnpkg/yarn/issues/4564)

If I do I'll require a CQ to copy the code from someone who's done it, however it does look hackish, the real fix should be done at `yarn`.

**Comment by marcdumais-work** [comment]
> If I do I'll require a CQ to copy the code from someone who's done it, however it does look hackish, the real fix should be done at `yarn`.

Yes, that really looks like a hack. Having windows CI for this repo is not pressing - let's wait to see if we get permission to fix the issue in yarn.

**Comment by vince-fugnitto** [comment]
> > If I do I'll require a CQ to copy the code from someone who's done it, however it does look hackish, the real fix should be done at `yarn`.
> 
> Yes, that really looks like a hack. Having windows CI for this repo is not pressing - let's wait to see if we get permission to fix the issue in yarn.

With @marechal-p help we were able to find a workaround, waiting for the CI to finish to see if it successfully worked :)

**Comment by vince-fugnitto** [comment]
@lmcbout @marcdumais-work 
It looks like all three operating systems (linux, macOS, windows) now passed using the workaround, is it fine to merge?

**Comment by lmcbout** [comment]
Your workaround does not come from the patch, you apply a postinstall and not the preinstalled as defined in the other PR (  https://github.com/yarnpkg/yarn/issues/4564 ). If we wait for `yarn ` to be fixed, it might take a while. This problem was reported 2 years ago and still not fixed, so the workaround sounds very good to me.
One thing if the file `download-adapters.js` is not there for any reasons, can we check for it and report and error to the end-user !

**Comment by vince-fugnitto** [comment]
> Your workaround does not come from the patch, you apply a postinstall and not the preinstalled as defined in the other PR ( [yarnpkg/yarn#4564](https://github.com/yarnpkg/yarn/issues/4564) ). 

There is no other fix as far as I know, the link you mentioned is an issue not a PR.


> One thing if the file `download-adapters.js` is not there for any reasons, can we check for it and report and error to the end-user !

The `download-adapters.js` script is defined in `@theia/debug` dependency.
The command will fail and report the error which I believe is enough of a report to end-users/developers. What more can we do?

**Comment by vince-fugnitto** [comment]
Updated the PR to split the changes into 2 commits:
1. replace `appveyor` with `travis ci` for windows
2. update the `postinstall` `dowload-debug-adapters` script for both `cortex-debug` and `cpp-debug`

**Pull request merged**
