### PR TITLE
Fix target electron-app

### PR DESCRIPTION
**Pull request by rcla**
#### What it does

Fixes: #121
Fix the target in electron-app

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@rcla thank you for your first contribution :+1: 

In order to accept the changes please be sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship (it is the reason for the failed CI check).

**Comment by rcla** [comment]
> @rcla thank you for your first contribution 👍
> 
> In order to accept the changes please be sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship (it is the reason for the failed CI check).

With pleasure.

I am a newbie to managing github.

Already update the commit with --signoff

**Comment by vince-fugnitto** [comment]
@rcla no problem and no rush :) please let me know when it's updated, at the moment the authorship looks incorrect (unknown), and the email is not yet registered for the eca:

Screen Shot 2021-06-21 at 12 17 15 PM


```
From 74489111d0eaf67c6c2a0840048b9fe2dcda37ae Mon Sep 17 00:00:00 2001
From: unknown <rclarosla@gmail.com>
Date: Sun, 20 Jun 2021 08:59:11 -0500
Subject: [PATCH] Fix target electron-app

---
 electron-app/package.json | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/electron-app/package.json b/electron-app/package.json
index e557ed9..e4d54c1 100644
--- a/electron-app/package.json
+++ b/electron-app/package.json
@@ -3,7 +3,7 @@
   "name": "electron-app",
   "version": "1.0.0",
   "theia": {
-    "target": "browser",
+    "target": "electron",
     "frontend": {
       "config": {
         "applicationName": "Theia C/C++ Extensions Example",
```

**Comment by rcla** [comment]
> please let me know when it's updated... ```

It is already updated.

**Comment by vince-fugnitto** [comment]
> > please let me know when it's updated... ```
> 
> It is already updated.

@rcla was the eca signed with rclarosla@gmail.com? It is still currently failing.

**Comment by rcla** [comment]
> > > please let me know when it's updated... ```
> > 
> > 
> > It is already updated.
> 
> @rcla was the eca signed with [rclarosla@gmail.com](mailto:rclarosla@gmail.com)? It is still currently failing.

SIngoff

**Comment by vince-fugnitto** [comment]
@rcla I'm not referring to the `sign-off`, I'm referring to the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) which I referenced [initially](https://github.com/eclipse-theia/theia-cpp-extensions/pull/122#pullrequestreview-688363977).

**Comment by rcla** [comment]
Just done

**Review by vince-fugnitto — APPROVED** [review]
Thank you for the updates 👍 The configuration should now be properly set for future contributions, even for the main framework :)

**Pull request merged**
