### PR TITLE
publish v1.0.0

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Publishes v1.0.0

#### How to test

Verify CI

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by marechal-p** [comment]
Silly question, but should we now target `"@theia/core":  "1"`  instead of latest?

@akosyakov what would you recommend?

**Comment by marcdumais-work** [comment]
> Silly question, but should we now target `"@theia/core": "1"` instead of latest?

I guess one advantage would be that, even without a `yarn.lock`, an app using `1` instead of `latest` would not try to pull the eventual `@theia/core@2.x`?

**Comment by marechal-p** [comment]
@marcdumais-work yes. We could also write it `^1.0.0`, but I think `1` is more simple.

**Comment by vince-fugnitto** [comment]
@marechal-p @marcdumais-work what is the accepted way forward?

**Comment by marcdumais-work** [comment]
> @marechal-p @marcdumais-work what is the accepted way forward?

I think it's ok to continue to use `latest` for now. It's easily changed later if we think something else is better. @marechal-p : ok with you?

**Pull request merged**
