### PR TITLE
Reset deps to 'next' following 1.0.0 release

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

Resets dependencies to `next` following the `v1.0.0` release.

#### How to test

Verify that CI passes.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
> the files (package.json) look fine, but travis did not compile

@lmcbout I cleared the cache and restarted the build.

**Comment by marechal-p** [comment]
Is it possible to do both commits at once (in one PR) next time? Would that be easier?

**Comment by vince-fugnitto** [comment]
> Is it possible to do both commits at once (in one PR) next time? Would that be easier?

I think we discussed the idea, but due to tagging we had to do two pull-requests?
cc @marcdumais-work

**Comment by marechal-p** [comment]
We tag commits, so one PR with 2 commits might work.

**Comment by marcdumais-work** [comment]
> We tag commits, so one PR with 2 commits might work.

True. The only downside is that the reviewers should make sure to look at the individual commits, since the 2nd one will undo stuff done in the 1st.

**Comment by vince-fugnitto** [comment]
> Is it possible to do both commits at once (in one PR) next time? Would that be easier?

I'll let you do the next release @marechal-p 😄

**Pull request merged**
