### PR TITLE
Show variables in memory view

### PR DESCRIPTION
**Pull request by marechal-p**
Rebased version of https://github.com/eclipse/theia-cpp-extension/pull/22 by @simark

### CODE REVIEW

**Comment by marechal-p** [comment]
Apparently there is a bug where we cannot scroll anymore.

**Comment by vince-fugnitto** [comment]
I've rebased the PR on the latest changes, and fixed the issue regarding the scrolling.

@marechal-p can you confirm that scrolling works correctly as before?

**Comment by colin-grant-work** [comment]
@marechal-p, @vince-fugnitto, This is a feature our users have been requesting. Is it still planned to merge this PR?

**Comment by vince-fugnitto** [comment]
> @marechal-p, @vince-fugnitto, This is a feature our users have been requesting. Is it still planned to merge this PR?

I believe so, it was forgotten for a while now so I'll rebase it and re-test.
Please let me know if you're interested in testing/contributing to the pull-request.

**Comment by vince-fugnitto** [comment]
Closing in favor of #111.

**Pull request closed without merging**
