### PR TITLE
Add stricter documentation checks

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Description:
- added stricter `tslint` documentation checks to ensure
that `enums`, `enum-members`, `functions`, `interfaces` and `properties`
are all properly documented.
- added `tslint` check to verify `no-dedundant-jsdoc` so that
documentation is concise and non-redudant compared to method signatures.
- updated the documentation so the checks pass.

Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@vince-fugnitto I noticed that linting is not working in this repo. I am working on a PR. I think that should go in first, since otherwise it's hard to avoid breaking the news rules when adding code.

**Comment by marcdumais-work** [comment]
https://github.com/eclipse-theia/theia-cpp-extensions/pull/64

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I noticed that linting is not working in this repo. I am working on a PR. I think that should go in first, since otherwise it's hard to avoid breaking the news rules when adding code.

Sure, sounds good to me.

**Comment by marcdumais-work** [comment]
#64 is merged. When you have a chance can you rebase on the new master?

**Comment by simark** [comment]
I think this is really cool, go doc!

**Comment by marcdumais-work** [comment]
Hi @thegecko FYI. 

Any objection about requiring stricter documentation in this repo?

**Comment by marcdumais-work** [comment]
@vince-fugnitto Since we plan to move `@theia/cpp` here, can you quickly evaluate how much work it will be to document it, as per the new linting rules, once we go ahead?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Since we plan to move `@theia/cpp` here, can you quickly evaluate how much work it will be to document it, as per the new linting rules, once we go ahead?

I verified and there are violations as per the new linting rules. 

It however does not look to be a big effort to update the code and can definitely be done either before the move, or as part of the PR for the move. Would you rather it'd be clean (update the documentation from the main repository) then perform the move?

**Comment by thegecko** [comment]
@marcdumais-work No concerns from me

**Pull request merged**
